name: Deploy to Hugging Face
on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["Merge Submission Data"]
    types:
      - completed
  # allow manual trigger from Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Git Identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Push Up Clean Repo without Submissions
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          mkdir hf-space-version
          rsync -av --progress ./ ./hf-space-version --exclude=submissions --exclude=.git --exclude=.github
          cd hf-space-version
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add origin https://huggingface_hub:${HF_TOKEN}@huggingface.co/spaces/DataAttributionEval/DATE-LM-Leaderboard
          git add .
          git commit -m "Clean Push to Hugging Face"
          git branch -M main
          git push -f origin main
